### ISSUE TITLE
ImportError: No module named wand.image

### ISSUE THREAD

**Issue by sawyeron** [xiaobocser/Mac-command-wallpaper#1]
```
$ bash set_desktop.sh source/risingabovethefog_2560x1440.jpg

set_desktop.sh: line 7: [: source/risingabovethefog_2560x1440.jpg: integer expression expected
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
Traceback (most recent call last):
  File "/Users/ouyang/Documents/code-wallpaper-2018-Mac/bin/generate_code_calender.py", line 36, in <module>
    main()
  File "/Users/ouyang/Documents/code-wallpaper-2018-Mac/bin/generate_code_calender.py", line 32, in main
    composite_image(week_num, pdf_path, pic_path, pic_save_path)
  File "/Users/ouyang/Documents/code-wallpaper-2018-Mac/bin/generate_code_calender.py", line 14, in composite_image
    with Image(filename=pdf_path.format(page), resolution=200) as calendar:
  File "/usr/local/lib/python3.6/site-packages/Wand-0.4.5-py3.6.egg/wand/image.py", line 2744, in __init__
  File "/usr/local/lib/python3.6/site-packages/Wand-0.4.5-py3.6.egg/wand/image.py", line 2822, in read
  File "/usr/local/lib/python3.6/site-packages/Wand-0.4.5-py3.6.egg/wand/resource.py", line 222, in raise_exception
wand.exceptions.BlobError: unable to open image `/Users/ouyang/source/2018_code_calendar.pdf': No such file or directory @ error/blob.c/OpenBlob/2735
Exception ignored in: <bound method Resource.__del__ of <wand.image.Image: (empty)>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/Wand-0.4.5-py3.6.egg/wand/resource.py", line 232, in __del__
  File "/usr/local/lib/python3.6/site-packages/Wand-0.4.5-py3.6.egg/wand/image.py", line 2767, in destroy
TypeError: object of type 'NoneType' has no len()
33:48: execution error: “Finder”遇到一个错误：AppleEvent 处理程序失败。 (-10000)
```
Python3 和默认的 Python 共存，报错😂

**Comment by xiaobocser** [comment]
谢谢反馈，非常抱歉，wand包安装忘了写进安装说明。

3. 安装wand包

`pip install wand`

ps. 也可以参考更新后的安装说明。

> 我用的py2.7，py3应该是通用的。如果还有问题，我可以用py3测试。

**Comment by sawyeron** [comment]
```
$ bash set_desktop.sh source/risingabovethefog_2560x1440.jpg

readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
python: can't open file 'bin/generate_code_calender.py': [Errno 2] No such file or directory
33:48: execution error: “Finder”遇到一个错误：AppleEvent 处理程序失败。 (-10000)
```
Wand 后来我自己安装了，但还是报错。

**Comment by xiaobocser** [comment]
报错是缺少`bin/generate_code_calender.py`这个文件导致的，你检查一下当前目录下是否有`bin`文件夹， 而且`bin`文件夹下是否有`generate_code_calender.py`文件，
