### ISSUE TITLE
日历无法生成

### ISSUE THREAD

**Issue by SongJasper** [xiaobocser/Mac-command-wallpaper#14]
brew install freetype imagemagick  (2.9.1)
brew install imagemagick@6 (6.9.9-49)  
 export MAGICK_HOME=/usr/local/opt/imagemagick@6
以上命令都已执行 括号内是对应版本 执行以下命令时依旧报错
./wallpaper randweb com
报错信息:
Traceback (most recent call last):
  File "bin/generate_code_calender.py", line 6, in <module>
    from wand.image import Image
  File "build/bdist.macosx-10.13-intel/egg/wand/image.py", line 20, in <module>
  File "build/bdist.macosx-10.13-intel/egg/wand/api.py", line 210, in <module>
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  brew install freetype imagemagick
33:48: execution error: “Finder”遇到一个错误：AppleEvent 处理程序失败。 (-10000)
希望能解决

**Comment by SongJasper** [comment]
已经解决
链接文件库 6.9.9-49是安装的版本号
ln -s /usr/local/Cellar/imagemagick@6/6.9.9-49/lib/libMagickWand-6.Q16.dylib /usr/local/lib/libMagickWand.dylib
https://github.com/ImageMagick/ImageMagick/issues/953
